### ISSUE TITLE
Unpublish extension

### ISSUE THREAD

**Issue by ssbarnea** [Naereen/Makefiles-support-for-VSCode#11]
Since Makefile support is not supported without plugin it make be better to remove extension from marketplace to avoid confusing users.

What do you think?

**Comment by Naereen** [comment]
Hi,
Yes, it's a good idea, I'll do it asap when I come back to my office.
Thanks for the suggestion.

**Comment by Naereen** [comment]
Done, https://marketplace.visualstudio.com/items?itemName=naereen.makefiles-support-for-vscode is dead.

**Comment by Naereen** [comment]
(https://code.visualstudio.com/docs/extensions/publish-extension#_unpublishing-extensions)
