### ISSUE TITLE
Feature Request: Symbol list for outline extension

### ISSUE THREAD

**Issue by bartosz-antosik** [Naereen/Makefiles-support-for-VSCode#5]
Do you think it would be possible to add symbol list which would allow extensions like [Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline)?

It would help browse esp. larger makefiles to get e.g. to desired target or variable.

**Comment by Naereen** [comment]
Hi!
I agree, this could be useful. I will look into the documentation to learn how to do that, and I will try.

**Comment by Naereen** [comment]
For the [go language extension](https://github.com/Microsoft/vscode-go/), [this script](https://github.com/Microsoft/vscode-go/blob/master/src/goOutline.ts) is used to call an external tool.
I will write a small bash script to parse Makefiles and provide a basic list of "rule/line" mapping, and then "variable/line" mapping, and try to use it with the above mentioned TS script.

**Comment by Naereen** [comment]
Example:
```bash
$ ./scripts/get-Makefile-outline.bash Makefile 
Input file 'Makefile' exists... working with it
- Printing list of rule:line for input file 'Makefile' ...
all:5
send:7
send_zamok:8
ls:11
test_getoutline:17
clean:20
package:23
publish:26
list_nb:33
list_html:35
html_notebooks:38
%.html:40
- Printing list of variable:line for input file 'Makefile' ...
SHELL:2
CONTENT_IPYNB:30
CONTENT_HTML:31
```

**Comment by Naereen** [comment]
I also tested it on a large Makefile, OCamlMakefile, and it works. Now I will try to include it in the extension, and use it to reply to [the API request of showing all symbols in file](https://code.visualstudio.com/docs/extensionAPI/language-support#_show-all-symbol-definitions-within-a-document).

**Comment by dbkaplun** [comment]
This would be great! Thanks for considering!

**Comment by Naereen** [comment]
@dbkaplun I don't think I'll try, as from now on there is an official VSCode extension to support Makefiles, see https://github.com/Microsoft/vscode/tree/master/extensions/make

**Comment by dbkaplun** [comment]
@Naereen how do I install it?

EDIT: just created Microsoft/vscode#47098.

**Comment by Naereen** [comment]
It's installed by default from v1.21…

**Comment by dbkaplun** [comment]
On 1.21.1, when I enter <kbd>Cmd+Shift+O</kbd> to open the Symbols List, I see this:

![symbols list](https://user-images.githubusercontent.com/1765130/38206190-75ab8cba-3677-11e8-9833-53247d95388b.png)

About code dialog:

![version](https://user-images.githubusercontent.com/1765130/38206211-957e8c9a-3677-11e8-84b4-398b85645964.png)

**Comment by Naereen** [comment]
Yes, so?
I didn't say that their extension implemented the "Symbol List" feature, I just said I won't work more on mine.

**Comment by Naereen** [comment]
Don't care, this repo is dead anyway.
